name: siprix_voip_sdk_platform_interface
description: A common platform interface for the Siprix VoIP SDK Flutter plugin.
homepage: https://siprix-voip.com
repository: https://github.com/siprix/FlutterPluginFederated/tree/main/siprix_voip_sdk_platform_interface
documentation: https://docs.siprix-voip.com
version: 1.0.2

environment:
  sdk: ^3.2.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

topics:
  - sip
  - voip
  - call
