name: siprix_voip_sdk
description: Siprix VoIP SDK plugin for embedding voice-over-IP (VoIP) audio/video calls based on SIP/RTP protocols into Flutter applications.
homepage: https://siprix-voip.com
repository: https://github.com/siprix/FlutterPluginFederated/tree/main/siprix_voip_sdk
documentation: https://docs.siprix-voip.com
version: 1.0.16

environment:
  sdk: ^3.2.0
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        default_package: siprix_voip_sdk_android
      ios:
        default_package: siprix_voip_sdk_ios
      linux:
        default_package: siprix_voip_sdk_linux
      macos:
        default_package: siprix_voip_sdk_macos
      windows:
        default_package: siprix_voip_sdk_windows

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.20.1
  siprix_voip_sdk_android: ^1.0.10
  siprix_voip_sdk_ios: ^1.0.15
  siprix_voip_sdk_linux: ^1.0.6
  siprix_voip_sdk_macos: ^1.0.6
  siprix_voip_sdk_windows: ^1.0.6
  siprix_voip_sdk_platform_interface: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

topics:
  - sip
  - voip
  - call
